apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-green
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
      version: green
  template:
    metadata:
      labels:
        app: user
        version: green
    spec:
      containers:
        - name: user
          image: preethamkmenon/user-service:v1
          ports:
            - containerPort: 3001
